# Pandas Practice – Kosovo vs Turkey Football Dataset

This notebook is a complete Pandas practice notebook using **`kosova_team.xlsx`**.

Each exercise contains:
- a clear request written in Markdown
- a solved code cell
- a short explanation of the idea used

The goal is to practice different Pandas techniques without repeating the same concept too many times.

## Dataset columns

The file contains football player statistics:

| Column | Meaning |
|---|---|
| `Player` | Player name |
| `Team` | National team |
| `Position` | Player position |
| `Goals` | Goals scored |
| `Assists` | Assists made |
| `Matches` | Matches played |
| `MinutesPlayed` | Total minutes played |
| `Rating` | Performance rating |

## Exercise 1 – Import Pandas and load the dataset

Load `kosova_team.xlsx` into a DataFrame called `df` and display the first 5 rows.

In [1]:
import pandas as pd

df = pd.read_excel('kosova_team.xlsx')
df.head()

,Player,Team,Position,Goals,Assists,Matches,MinutesPlayed,Rating
0,Vedat Muriqi,Kosovo,Forward,5,2,6,520,7.50
1,Milot Rashica,Kosovo,Winger,3,4,6,540,7.30
2,Amir Rrahmani,Kosovo,Defender,1,0,6,600,7.10
3,Florent Muslija,Kosovo,Midfielder,2,2,5,420,7.00
4,Elbasan Rashani,Kosovo,Winger,2,1,5,390,6.90

**Explanation:** `pd.read_excel()` reads the Excel file and creates a DataFrame. `head()` is used to quickly inspect the first rows.

## Exercise 2 – Basic dataset inspection

Display:
- number of rows and columns
- column names
- general DataFrame information

In [2]:
print('Shape:', df.shape)
print('\nColumns:')
print(df.columns.tolist())

print('\nDataFrame info:')
df.info()

Shape: (31, 8)

Columns:
['Player', 'Team', 'Position', 'Goals', 'Assists', 'Matches', 'MinutesPlayed', 'Rating']

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         31 non-null     object
 1   Team           31 non-null     object
 2   Position       31 non-null     object
 3   Goals          31 non-null     int64
 4   Assists        31 non-null     int64
 5   Matches        31 non-null     int64
 6   MinutesPlayed  31 non-null     int64
 7   Rating         31 non-null     float64
dtypes: float64(1), int64(4), object(3)
memory usage: 2.1+ KB

**Explanation:** `shape` shows dataset size, `columns` shows field names, and `info()` shows data types and missing-value counts.

## Exercise 3 – Check missing values and duplicates

Check if the dataset contains:
- missing values
- duplicated rows

In [3]:
missing_values = df.isna().sum()
duplicated_rows = df.duplicated().sum()

print('Missing values per column:')
print(missing_values)

print('\nNumber of duplicated rows:', duplicated_rows)

Missing values per column:
Player           0
Team             0
Position         0
Goals            0
Assists          0
Matches          0
MinutesPlayed    0
Rating           0
dtype: int64

Number of duplicated rows: 0

**Explanation:** `isna().sum()` counts missing values per column. `duplicated().sum()` counts full duplicated rows.

## Exercise 4 – Select specific columns

Select only these columns and show the first 10 rows:

`Player`, `Team`, `Position`, `Rating`

In [4]:
player_overview = df[['Player', 'Team', 'Position', 'Rating']]
player_overview.head(10)

            Player    Team    Position  Rating
0     Vedat Muriqi  Kosovo     Forward    7.50
1    Milot Rashica  Kosovo      Winger    7.30
2    Amir Rrahmani  Kosovo    Defender    7.10
3  Florent Muslija  Kosovo  Midfielder    7.00
4  Elbasan Rashani  Kosovo      Winger    6.90
5    Valon Berisha  Kosovo  Midfielder    7.00
6  Bernard Berisha  Kosovo      Winger    7.10
7   Mërgim Vojvoda  Kosovo    Defender    6.80
8      Fidan Aliti  Kosovo    Defender    6.90
9     Samir Ujkani  Kosovo  Goalkeeper    7.00

**Explanation:** Double square brackets are used to select multiple columns from a DataFrame.

## Exercise 5 – Filter rows with one condition

Find all players who belong to **Kosovo**.

Display only:
`Player`, `Position`, `Goals`, `Assists`, `Rating`

In [5]:
kosovo_players = df.loc[df['Team'] == 'Kosovo', ['Player', 'Position', 'Goals', 'Assists', 'Rating']]
kosovo_players

             Player    Position  Goals  Assists  Rating
0      Vedat Muriqi     Forward      5        2    7.50
1     Milot Rashica      Winger      3        4    7.30
2     Amir Rrahmani    Defender      1        0    7.10
3   Florent Muslija  Midfielder      2        2    7.00
4   Elbasan Rashani      Winger      2        1    6.90
5     Valon Berisha  Midfielder      1        2    7.00
6   Bernard Berisha      Winger      1        3    7.10
7    Mërgim Vojvoda    Defender      0        1    6.80
8       Fidan Aliti    Defender      0        0    6.90
9      Samir Ujkani  Goalkeeper      0        0    7.00
10   Arijanet Muric  Goalkeeper      0        0    6.80
11    Betim Fazliji  Midfielder      0        1    6.70
12  Hekuran Kryeziu  Midfielder      0        0    6.60
13     Altin Zeqiri     Forward      1        0    6.70
14   Donat Rrudhani  Midfielder      1        1    6.90
15   Lirim Kastrati      Winger      2        2    7.00

**Explanation:** `loc[row_condition, selected_columns]` filters rows and selects columns in one clean step.

## Exercise 6 – Filter rows using `isin()`

Find all players whose position is **Winger** or **Forward**.

In [6]:
attackers = df[df['Position'].isin(['Winger', 'Forward'])]
attackers[['Player', 'Team', 'Position', 'Goals', 'Assists', 'Rating']]

                Player    Team Position  Goals  Assists  Rating
0         Vedat Muriqi  Kosovo  Forward      5        2    7.50
1        Milot Rashica  Kosovo   Winger      3        4    7.30
4      Elbasan Rashani  Kosovo   Winger      2        1    6.90
6      Bernard Berisha  Kosovo   Winger      1        3    7.10
13        Altin Zeqiri  Kosovo  Forward      1        0    6.70
15      Lirim Kastrati  Kosovo   Winger      2        2    7.00
17        Cengiz Ünder  Turkey   Winger      3        3    7.40
20    Kerem Aktürkoğlu  Turkey   Winger      3        2    7.20
21        Burak Yılmaz  Turkey  Forward      2        1    7.00
22           Enes Ünal  Turkey  Forward      2        2    7.10
29  Barış Alper Yılmaz  Turkey   Winger      1        1    6.90

**Explanation:** `isin()` is useful when a column can match one of several possible values.

## Exercise 7 – Filter with multiple conditions

Find players who:
- played at least 5 matches
- have a rating greater than 7.0

Display the result sorted by rating from highest to lowest.

In [7]:
consistent_high_rated = df[(df['Matches'] >= 5) & (df['Rating'] > 7.0)]
consistent_high_rated.sort_values('Rating', ascending=False)

,Player,Team,Position,Goals,Assists,Matches,MinutesPlayed,Rating
16,Hakan Çalhanoğlu,Turkey,Midfielder,4,5,6,580,7.80
0,Vedat Muriqi,Kosovo,Forward,5,2,6,520,7.50
17,Cengiz Ünder,Turkey,Winger,3,3,6,500,7.40
1,Milot Rashica,Kosovo,Winger,3,4,6,540,7.30
19,Orkun Kökçü,Turkey,Midfielder,2,3,6,520,7.30
24,Çağlar Söyüncü,Turkey,Defender,1,0,6,600,7.30
18,Merih Demiral,Turkey,Defender,1,1,6,600,7.20
20,Kerem Aktürkoğlu,Turkey,Winger,3,2,5,450,7.20
25,Uğurcan Çakır,Turkey,Goalkeeper,0,0,6,600,7.20
2,Amir Rrahmani,Kosovo,Defender,1,0,6,600,7.10
6,Bernard Berisha,Kosovo,Winger,1,3,5,400,7.10
22,Enes Ünal,Turkey,Forward,2,2,5,420,7.10

**Explanation:** Use `&` for AND conditions in Pandas. Each condition must be inside parentheses.

## Exercise 8 – Create a new calculated column

Create a new column called `GoalContribution`:

`GoalContribution = Goals + Assists`

Then display `Player`, `Team`, `Goals`, `Assists`, and `GoalContribution`.

In [8]:
df['GoalContribution'] = df['Goals'] + df['Assists']
df[['Player', 'Team', 'Goals', 'Assists', 'GoalContribution']].head(10)

            Player    Team  Goals  Assists  GoalContribution
0     Vedat Muriqi  Kosovo      5        2                 7
1    Milot Rashica  Kosovo      3        4                 7
2    Amir Rrahmani  Kosovo      1        0                 1
3  Florent Muslija  Kosovo      2        2                 4
4  Elbasan Rashani  Kosovo      2        1                 3
5    Valon Berisha  Kosovo      1        2                 3
6  Bernard Berisha  Kosovo      1        3                 4
7   Mërgim Vojvoda  Kosovo      0        1                 1
8      Fidan Aliti  Kosovo      0        0                 0
9     Samir Ujkani  Kosovo      0        0                 0

**Explanation:** A new column can be created by assigning a calculation to `df['NewColumn']`.

## Exercise 9 – Create a ratio column safely

Create `MinutesPerMatch`:

`MinutesPerMatch = MinutesPlayed / Matches`

Show the top 10 players with the highest minutes per match.

In [9]:
df['MinutesPerMatch'] = df['MinutesPlayed'] / df['Matches']

df[['Player', 'Team', 'Position', 'Matches', 'MinutesPlayed', 'MinutesPerMatch']].sort_values('MinutesPerMatch', ascending=False).head(10)

,Player,Team,Position,Matches,MinutesPlayed,MinutesPerMatch
2,Amir Rrahmani,Kosovo,Defender,6,600,100.00
9,Samir Ujkani,Kosovo,Goalkeeper,6,600,100.00
18,Merih Demiral,Turkey,Defender,6,600,100.00
24,Çağlar Söyüncü,Turkey,Defender,6,600,100.00
25,Uğurcan Çakır,Turkey,Goalkeeper,6,600,100.00
16,Hakan Çalhanoğlu,Turkey,Midfielder,6,580,96.67
8,Fidan Aliti,Kosovo,Defender,6,580,96.67
30,Abdülkerim Bardakcı,Turkey,Defender,5,480,96.00
7,Mërgim Vojvoda,Kosovo,Defender,6,560,93.33
23,Zeki Çelik,Turkey,Defender,6,560,93.33

**Explanation:** This creates a per-match metric, which is more comparable than total minutes alone.

## Exercise 10 – Sort data

Sort all players by:
1. `Rating` descending
2. `GoalContribution` descending

Show the top 8 players.

In [10]:
top_players = df.sort_values(['Rating', 'GoalContribution'], ascending=[False, False])
top_players.head(8)

,Player,Team,Position,Goals,Assists,Matches,MinutesPlayed,Rating,GoalContribution,MinutesPerMatch
16,Hakan Çalhanoğlu,Turkey,Midfielder,4,5,6,580,7.80,9,96.67
0,Vedat Muriqi,Kosovo,Forward,5,2,6,520,7.50,7,86.67
17,Cengiz Ünder,Turkey,Winger,3,3,6,500,7.40,6,83.33
1,Milot Rashica,Kosovo,Winger,3,4,6,540,7.30,7,90.00
19,Orkun Kökçü,Turkey,Midfielder,2,3,6,520,7.30,5,86.67
24,Çağlar Söyüncü,Turkey,Defender,1,0,6,600,7.30,1,100.00
20,Kerem Aktürkoğlu,Turkey,Winger,3,2,5,450,7.20,5,90.00
18,Merih Demiral,Turkey,Defender,1,1,6,600,7.20,2,100.00

**Explanation:** `sort_values()` can sort by multiple columns. The `ascending` list controls each column separately.

## Exercise 11 – Find the best player by one column

Find the single player with the highest `MinutesPlayed`.

In [11]:
most_minutes_player = df.loc[df['MinutesPlayed'].idxmax()]
most_minutes_player

Player              Amir Rrahmani
Team                       Kosovo
Position                 Defender
Goals                           1
Assists                         0
Matches                         6
MinutesPlayed                 600
Rating                       7.10
GoalContribution                1
MinutesPerMatch            100.00
Name: 2, dtype: object

**Explanation:** `idxmax()` returns the index of the highest value. `loc[]` then returns that full row.

## Exercise 12 – Count values by category

Count how many players there are in each `Position`.

In [12]:
position_counts = df['Position'].value_counts()
position_counts

Position
Midfielder    9
Defender      7
Winger        7
Forward       4
Goalkeeper    4
Name: count, dtype: int64

**Explanation:** `value_counts()` is used for frequency counts of categories.

## Exercise 13 – Average rating by team

Calculate the average `Rating` for each team.

In [13]:
average_rating_by_team = df.groupby('Team')['Rating'].mean().sort_values(ascending=False)
average_rating_by_team

Team
Turkey   7.14
Kosovo   6.96
Name: Rating, dtype: float64

**Explanation:** `groupby()` splits the data by team, then `mean()` calculates the average rating for each group.

## Exercise 14 – Multiple aggregations by position

Group by `Position` and calculate:
- average goals
- average assists
- average rating
- total players

In [14]:
position_summary = (
    df.groupby('Position')
      .agg(
          Players=('Player', 'count'),
          AvgGoals=('Goals', 'mean'),
          AvgAssists=('Assists', 'mean'),
          AvgRating=('Rating', 'mean')
      )
      .sort_values('AvgRating', ascending=False)
)

position_summary

            Players  AvgGoals  AvgAssists  AvgRating
Position
Winger            7      2.14        2.29       7.11
Forward           4      2.50        1.25       7.08
Defender          7      0.43        0.71       7.04
Goalkeeper        4      0.00        0.00       7.00
Midfielder        9      1.11        1.67       7.00

**Explanation:** Named aggregation with `.agg()` creates a clean summary table with custom column names.

## Exercise 15 – Team summary table

Create a summary table with one row per team and these columns:
- number of players
- total goals
- total assists
- average rating
- total minutes played

In [15]:
team_summary = (
    df.groupby('Team')
      .agg(
          Players=('Player', 'count'),
          TotalGoals=('Goals', 'sum'),
          TotalAssists=('Assists', 'sum'),
          AvgRating=('Rating', 'mean'),
          TotalMinutes=('MinutesPlayed', 'sum')
      )
      .sort_values('AvgRating', ascending=False)
)

team_summary

        Players  TotalGoals  TotalAssists  AvgRating  TotalMinutes
Team
Turkey       15          19            22       7.14          7000
Kosovo       16          19            19       6.96          7010

**Explanation:** This is a typical reporting-style summary using `groupby()` and multiple aggregations.

## Exercise 16 – String filtering

Find all players whose name contains **`Rash`**.

In [16]:
rash_players = df[df['Player'].str.contains('Rash', case=False, na=False)]
rash_players[['Player', 'Team', 'Position', 'Goals', 'Assists', 'Rating']]

            Player    Team Position  Goals  Assists  Rating
1    Milot Rashica  Kosovo   Winger      3        4    7.30
4  Elbasan Rashani  Kosovo   Winger      2        1    6.90

**Explanation:** `str.contains()` searches inside text columns. `case=False` makes the search case-insensitive.

## Exercise 17 – Use `loc` to create a category column

Create a new column called `StarPlayer`:
- `Yes` if `Rating >= 7.3`
- `No` otherwise

Display `Player`, `Team`, `Rating`, and `StarPlayer`.

In [17]:
df['StarPlayer'] = 'No'
df.loc[df['Rating'] >= 7.3, 'StarPlayer'] = 'Yes'

df[['Player', 'Team', 'Rating', 'StarPlayer']].sort_values('Rating', ascending=False)

                 Player    Team  Rating StarPlayer
16     Hakan Çalhanoğlu  Turkey    7.80        Yes
0          Vedat Muriqi  Kosovo    7.50        Yes
17         Cengiz Ünder  Turkey    7.40        Yes
24       Çağlar Söyüncü  Turkey    7.30        Yes
19          Orkun Kökçü  Turkey    7.30        Yes
1         Milot Rashica  Kosovo    7.30        Yes
20     Kerem Aktürkoğlu  Turkey    7.20         No
18        Merih Demiral  Turkey    7.20         No
25        Uğurcan Çakır  Turkey    7.20         No
22            Enes Ünal  Turkey    7.10         No
2         Amir Rrahmani  Kosovo    7.10         No
6       Bernard Berisha  Kosovo    7.10         No
3       Florent Muslija  Kosovo    7.00         No
5         Valon Berisha  Kosovo    7.00         No
9          Samir Ujkani  Kosovo    7.00         No
21         Burak Yılmaz  Turkey    7.00         No
15       Lirim Kastrati  Kosovo    7.00         No
23           Zeki Çelik  Turkey    7.00         No
26       Altay Bayındır  Turkey    7.00         No
30  Abdülkerim Bardakcı  Turkey    7.00         No
14       Donat Rrudhani  Kosovo    6.90         No
8           Fidan Aliti  Kosovo    6.90         No
4       Elbasan Rashani  Kosovo    6.90         No
29   Barış Alper Yılmaz  Turkey    6.90         No
27          Salih Özcan  Turkey    6.90         No
7        Mërgim Vojvoda  Kosovo    6.80         No
10       Arijanet Muric  Kosovo    6.80         No
28         Okay Yokuşlu  Turkey    6.80         No
11        Betim Fazliji  Kosovo    6.70         No
13         Altin Zeqiri  Kosovo    6.70         No
12      Hekuran Kryeziu  Kosovo    6.60         No

**Explanation:** `loc` can update values only where a condition is true.

## Exercise 18 – Use `apply()` for custom logic

Create a column called `PerformanceLevel` using this logic:
- `Excellent` if rating is 7.5 or higher
- `Good` if rating is from 7.0 to below 7.5
- `Average` if rating is below 7.0

In [18]:
def classify_performance(rating):
    if rating >= 7.5:
        return 'Excellent'
    elif rating >= 7.0:
        return 'Good'
    else:
        return 'Average'


df['PerformanceLevel'] = df['Rating'].apply(classify_performance)
df[['Player', 'Team', 'Rating', 'PerformanceLevel']].sort_values('Rating', ascending=False)

                 Player    Team  Rating PerformanceLevel
16     Hakan Çalhanoğlu  Turkey    7.80        Excellent
0          Vedat Muriqi  Kosovo    7.50        Excellent
17         Cengiz Ünder  Turkey    7.40             Good
24       Çağlar Söyüncü  Turkey    7.30             Good
19          Orkun Kökçü  Turkey    7.30             Good
1         Milot Rashica  Kosovo    7.30             Good
20     Kerem Aktürkoğlu  Turkey    7.20             Good
18        Merih Demiral  Turkey    7.20             Good
25        Uğurcan Çakır  Turkey    7.20             Good
22            Enes Ünal  Turkey    7.10             Good
2         Amir Rrahmani  Kosovo    7.10             Good
6       Bernard Berisha  Kosovo    7.10             Good
3       Florent Muslija  Kosovo    7.00             Good
5         Valon Berisha  Kosovo    7.00             Good
9          Samir Ujkani  Kosovo    7.00             Good
21         Burak Yılmaz  Turkey    7.00             Good
15       Lirim Kastrati  Kosovo    7.00             Good
23           Zeki Çelik  Turkey    7.00             Good
26       Altay Bayındır  Turkey    7.00             Good
30  Abdülkerim Bardakcı  Turkey    7.00             Good
14       Donat Rrudhani  Kosovo    6.90          Average
8           Fidan Aliti  Kosovo    6.90          Average
4       Elbasan Rashani  Kosovo    6.90          Average
29   Barış Alper Yılmaz  Turkey    6.90          Average
27          Salih Özcan  Turkey    6.90          Average
7        Mërgim Vojvoda  Kosovo    6.80          Average
10       Arijanet Muric  Kosovo    6.80          Average
28         Okay Yokuşlu  Turkey    6.80          Average
11        Betim Fazliji  Kosovo    6.70          Average
13         Altin Zeqiri  Kosovo    6.70          Average
12      Hekuran Kryeziu  Kosovo    6.60          Average

**Explanation:** `apply()` is useful when the logic is easier to write as a Python function.

## Exercise 19 – Use `groupby()` with `transform()`

Create a new column called `TeamAvgRating` that contains each player's team average rating.

Then create `RatingDifferenceFromTeam`:

`RatingDifferenceFromTeam = Rating - TeamAvgRating`

Show the players with the highest positive difference.

In [19]:
df['TeamAvgRating'] = df.groupby('Team')['Rating'].transform('mean')
df['RatingDifferenceFromTeam'] = df['Rating'] - df['TeamAvgRating']

rating_difference = df[['Player', 'Team', 'Rating', 'TeamAvgRating', 'RatingDifferenceFromTeam']]     .sort_values('RatingDifferenceFromTeam', ascending=False)

rating_difference.head(10)

              Player    Team  Rating  TeamAvgRating  RatingDifferenceFromTeam
16  Hakan Çalhanoğlu  Turkey    7.80           7.14                      0.66
0       Vedat Muriqi  Kosovo    7.50           6.96                      0.54
1      Milot Rashica  Kosovo    7.30           6.96                      0.34
17      Cengiz Ünder  Turkey    7.40           7.14                      0.26
19       Orkun Kökçü  Turkey    7.30           7.14                      0.16
24    Çağlar Söyüncü  Turkey    7.30           7.14                      0.16
2      Amir Rrahmani  Kosovo    7.10           6.96                      0.14
6    Bernard Berisha  Kosovo    7.10           6.96                      0.14
25     Uğurcan Çakır  Turkey    7.20           7.14                      0.06
18     Merih Demiral  Turkey    7.20           7.14                      0.06

**Explanation:** `transform()` returns a value for every original row, so it is perfect when we need group statistics inside the original DataFrame.

## Exercise 20 – Find players with assists but no goals

Find players who have:
- `Goals == 0`
- `Assists >= 1`

In [20]:
assist_no_goal = df[(df['Goals'] == 0) & (df['Assists'] >= 1)]
assist_no_goal[['Player', 'Team', 'Position', 'Goals', 'Assists', 'Rating']]

                 Player    Team    Position  Goals  Assists  Rating
7        Mërgim Vojvoda  Kosovo    Defender      0        1    6.80
11        Betim Fazliji  Kosovo  Midfielder      0        1    6.70
23           Zeki Çelik  Turkey    Defender      0        2    7.00
27          Salih Özcan  Turkey  Midfielder      0        1    6.90
30  Abdülkerim Bardakcı  Turkey    Defender      0        1    7.00

**Explanation:** This combines two numeric conditions using `&`.

## Exercise 21 – Pivot table

Create a pivot table showing total goals by:
- rows: `Position`
- columns: `Team`

Fill missing values with 0.

In [21]:
goals_pivot = pd.pivot_table(
    df,
    values='Goals',
    index='Position',
    columns='Team',
    aggfunc='sum',
    fill_value=0
)

goals_pivot

Team        Kosovo  Turkey
Position
Defender         1       2
Forward          6       4
Goalkeeper       0       0
Midfielder       4       6
Winger           8       7

**Explanation:** A pivot table reshapes grouped results into a more report-friendly table.

## Exercise 22 – Compare teams by position

Create a table that shows the average rating for each combination of `Team` and `Position`.

In [22]:
team_position_rating = (
    df.groupby(['Team', 'Position'])['Rating']
      .mean()
      .reset_index()
      .sort_values(['Team', 'Rating'], ascending=[True, False])
)

team_position_rating

     Team    Position  Rating
1  Kosovo     Forward    7.10
4  Kosovo      Winger    7.08
0  Kosovo    Defender    6.93
2  Kosovo  Goalkeeper    6.90
3  Kosovo  Midfielder    6.84
8  Turkey  Midfielder    7.20
9  Turkey      Winger    7.17
5  Turkey    Defender    7.12
7  Turkey  Goalkeeper    7.10
6  Turkey     Forward    7.05

**Explanation:** Grouping by multiple columns allows us to analyze combinations, not only one category at a time.

## Exercise 23 – Query method

Use `.query()` to find players from **Turkey** with rating at least **7.2**.

In [23]:
turkey_top_players = df.query("Team == 'Turkey' and Rating >= 7.2")
turkey_top_players[['Player', 'Team', 'Position', 'Rating', 'GoalContribution']]

              Player    Team    Position  Rating  GoalContribution
16  Hakan Çalhanoğlu  Turkey  Midfielder    7.80                 9
17      Cengiz Ünder  Turkey      Winger    7.40                 6
18     Merih Demiral  Turkey    Defender    7.20                 2
19       Orkun Kökçü  Turkey  Midfielder    7.30                 5
20  Kerem Aktürkoğlu  Turkey      Winger    7.20                 5
24    Çağlar Söyüncü  Turkey    Defender    7.30                 1
25     Uğurcan Çakır  Turkey  Goalkeeper    7.20                 0

**Explanation:** `.query()` can make filtering expressions easier to read, especially for simple conditions.

## Exercise 24 – Export the final DataFrame

Export the updated DataFrame to a new Excel file named:

`kosova_team_with_solutions.xlsx`

The exported file should include all new columns created in this notebook.

In [24]:
df.to_excel('kosova_team_with_solutions.xlsx', index=False)
print('File exported successfully: kosova_team_with_solutions.xlsx')

File exported successfully: kosova_team_with_solutions.xlsx

**Explanation:** `to_excel()` saves the DataFrame as an Excel file. `index=False` avoids exporting the Pandas index as an extra column.

## Final recap

In this notebook, students practiced:

- loading Excel data
- inspecting rows, columns, data types, missing values, and duplicates
- selecting columns
- filtering with one or multiple conditions
- using `isin()` and string filters
- creating calculated columns
- sorting data
- using `groupby()`, `.agg()`, and `transform()`
- creating pivot tables
- exporting results to Excel