# Pandas Recap Exercises – Transactions Dataset

This notebook is prepared as a **student-ready Pandas exercise with full solutions**.

Dataset used: `Transactions.xlsx`

## Main topics covered

- Loading Excel data
- Inspecting DataFrames
- Selecting columns and rows
- Conditional filtering
- Creating calculated columns
- Sorting
- Aggregations
- `groupby`
- `value_counts`
- `idxmax`
- `transform`
- `pivot_table`
- Exporting results to Excel

## 0. Import Pandas and Load the Dataset

**Request:**  
Import pandas and load the Excel file `Transactions.xlsx` into a DataFrame named `df`.

**Explanation:**  
`pd.read_excel()` reads an Excel file and converts it into a Pandas DataFrame.

In [1]:
import pandas as pd

df = pd.read_excel("Transactions.xlsx")

df.head()

   TransactionID Customer  Product     Category  Quantity  Price
0              1    Alice   Laptop  Electronics         1   1000
1              2      Bob    Phone  Electronics         2    500
2              3  Charlie   Tablet  Electronics         1    300
3              4    David    Shoes      Fashion         3     50
4              5     Emma  T-Shirt      Fashion         2     20

## 1. Display the First and Last Rows

**Request:**  
Display the first 5 rows and the last 5 rows of the dataset.

**Explanation:**  
`head()` shows rows from the beginning, while `tail()` shows rows from the end.

In [2]:
df.head()

   TransactionID Customer  Product     Category  Quantity  Price
0              1    Alice   Laptop  Electronics         1   1000
1              2      Bob    Phone  Electronics         2    500
2              3  Charlie   Tablet  Electronics         1    300
3              4    David    Shoes      Fashion         3     50
4              5     Emma  T-Shirt      Fashion         2     20

In [3]:
df.tail()

    TransactionID Customer  Product     Category  Quantity  Price
15             16    Alice    Shoes      Fashion         3     50
16             17      Bob  T-Shirt      Fashion         2     20
17             18  Charlie   Laptop  Electronics         1   1000
18             19    David    Phone  Electronics         2    500
19             20     Emma   Tablet  Electronics         3    300

## 2. Check the Shape of the Dataset

**Request:**  
Find how many rows and columns the dataset has.

**Explanation:**  
`shape` returns a tuple in this format: `(number_of_rows, number_of_columns)`.

In [4]:
df.shape

(20, 6)

## 3. Display Column Names and Data Types

**Request:**  
Display all column names and check the data type of each column.

**Explanation:**  
`columns` shows column names, while `dtypes` shows the data type of each column.

In [5]:
df.columns

Index(['TransactionID', 'Customer', 'Product', 'Category', 'Quantity',
       'Price'],
      dtype='object')

In [6]:
df.dtypes

TransactionID     int64
Customer         object
Product          object
Category         object
Quantity          int64
Price             int64
dtype: object

## 4. General Dataset Information

**Request:**  
Use Pandas to display a technical summary of the DataFrame.

**Explanation:**  
`info()` shows columns, non-null values, and data types.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionID  20 non-null     int64
 1   Customer       20 non-null     object
 2   Product        20 non-null     object
 3   Category       20 non-null     object
 4   Quantity       20 non-null     int64
 5   Price          20 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.1+ KB

## 5. Check for Missing Values

**Request:**  
Check if the dataset contains missing values.

**Explanation:**  
`isna()` checks for missing values, and `sum()` counts them per column.

In [8]:
df.isna().sum()

TransactionID    0
Customer         0
Product          0
Category         0
Quantity         0
Price            0
dtype: int64

## 6. Select One Column

**Request:**  
Select only the `Customer` column.

**Explanation:**  
A single column can be selected using square brackets.

In [9]:
df["Customer"]

0       Alice
1         Bob
2     Charlie
3       David
4        Emma
5       Alice
6         Bob
7     Charlie
8       David
9        Emma
10      Alice
11        Bob
12    Charlie
13      David
14       Emma
15      Alice
16        Bob
17    Charlie
18      David
19       Emma
Name: Customer, dtype: object

## 7. Select Multiple Columns

**Request:**  
Select only the `Customer`, `Product`, and `Price` columns.

**Explanation:**  
Multiple columns are selected by passing a list of column names.

In [10]:
df[["Customer", "Product", "Price"]]

   Customer  Product  Price
0     Alice   Laptop   1000
1       Bob    Phone    500
2   Charlie   Tablet    300
3     David    Shoes     50
4      Emma  T-Shirt     20
5     Alice    Phone    500
6       Bob   Tablet    300
7   Charlie   Laptop   1000
8     David    Shoes     50
9      Emma  T-Shirt     20
10    Alice   Laptop   1000
11      Bob    Shoes     50
12  Charlie  T-Shirt     20
13    David    Phone    500
14     Emma   Tablet    300
15    Alice    Shoes     50
16      Bob  T-Shirt     20
17  Charlie   Laptop   1000
18    David    Phone    500
19     Emma   Tablet    300

## 8. Select Specific Rows and Columns with `loc`

**Request:**  
Display the `Customer`, `Product`, and `Price` columns for the first 5 rows.

**Explanation:**  
`loc` is label-based. Here we use row labels `0:4` and selected column names.

In [11]:
df.loc[0:4, ["Customer", "Product", "Price"]]

  Customer  Product  Price
0    Alice   Laptop   1000
1      Bob    Phone    500
2  Charlie   Tablet    300
3    David    Shoes     50
4     Emma  T-Shirt     20

## 9. Select Specific Rows and Columns with `iloc`

**Request:**  
Display the first 5 rows and first 3 columns using index positions.

**Explanation:**  
`iloc` is position-based. It uses numeric row and column positions.

In [12]:
df.iloc[0:5, 0:3]

   TransactionID Customer  Product
0              1    Alice   Laptop
1              2      Bob    Phone
2              3  Charlie   Tablet
3              4    David    Shoes
4              5     Emma  T-Shirt

## 10. Filter Electronics Transactions

**Request:**  
Find all transactions where `Category` is `Electronics`.

**Explanation:**  
A condition returns `True` or `False` for each row. Pandas keeps only rows where the condition is `True`.

In [13]:
electronics = df[df["Category"] == "Electronics"]

electronics

    TransactionID Customer Product     Category  Quantity  Price
0               1    Alice  Laptop  Electronics         1   1000
1               2      Bob   Phone  Electronics         2    500
2               3  Charlie  Tablet  Electronics         1    300
5               6    Alice   Phone  Electronics         1    500
6               7      Bob  Tablet  Electronics         2    300
7               8  Charlie  Laptop  Electronics         3   1000
10             11    Alice  Laptop  Electronics         1   1000
13             14    David   Phone  Electronics         2    500
14             15     Emma  Tablet  Electronics         1    300
17             18  Charlie  Laptop  Electronics         1   1000
18             19    David   Phone  Electronics         2    500
19             20     Emma  Tablet  Electronics         3    300

## 11. Filter Transactions with Quantity Greater Than 1

**Request:**  
Find all transactions where `Quantity` is greater than 1.

In [14]:
df[df["Quantity"] > 1]

    TransactionID Customer  Product     Category  Quantity  Price
1               2      Bob    Phone  Electronics         2    500
3               4    David    Shoes      Fashion         3     50
4               5     Emma  T-Shirt      Fashion         2     20
6               7      Bob   Tablet  Electronics         2    300
7               8  Charlie   Laptop  Electronics         3   1000
9              10     Emma  T-Shirt      Fashion         2     20
11             12      Bob    Shoes      Fashion         2     50
12             13  Charlie  T-Shirt      Fashion         3     20
13             14    David    Phone  Electronics         2    500
15             16    Alice    Shoes      Fashion         3     50
16             17      Bob  T-Shirt      Fashion         2     20
18             19    David    Phone  Electronics         2    500
19             20     Emma   Tablet  Electronics         3    300

## 12. Filter Using Multiple Conditions

**Request:**  
Find all transactions where:

- `Category` is `Fashion`
- `Quantity` is at least 2

**Explanation:**  
Use `&` for AND conditions. Each condition should be inside parentheses.

In [15]:
fashion_quantity = df[
    (df["Category"] == "Fashion") &
    (df["Quantity"] >= 2)
]

fashion_quantity

    TransactionID Customer  Product Category  Quantity  Price
3               4    David    Shoes  Fashion         3     50
4               5     Emma  T-Shirt  Fashion         2     20
9              10     Emma  T-Shirt  Fashion         2     20
11             12      Bob    Shoes  Fashion         2     50
12             13  Charlie  T-Shirt  Fashion         3     20
15             16    Alice    Shoes  Fashion         3     50
16             17      Bob  T-Shirt  Fashion         2     20

## 13. Filter Using `isin`

**Request:**  
Find all transactions where the product is either `Laptop` or `Phone`.

**Explanation:**  
`isin()` is useful when checking if a value belongs to a list of allowed values.

In [16]:
df[df["Product"].isin(["Laptop", "Phone"])]

    TransactionID Customer Product     Category  Quantity  Price
0               1    Alice  Laptop  Electronics         1   1000
1               2      Bob   Phone  Electronics         2    500
5               6    Alice   Phone  Electronics         1    500
7               8  Charlie  Laptop  Electronics         3   1000
10             11    Alice  Laptop  Electronics         1   1000
13             14    David   Phone  Electronics         2    500
17             18  Charlie  Laptop  Electronics         1   1000
18             19    David   Phone  Electronics         2    500

## 14. Create a Total Column

**Request:**  
Create a new column named `Total`, calculated as:

`Quantity * Price`

**Explanation:**  
This creates the total value of each transaction.

In [17]:
df["Total"] = df["Quantity"] * df["Price"]

df.head()

   TransactionID Customer  Product     Category  Quantity  Price  Total
0              1    Alice   Laptop  Electronics         1   1000   1000
1              2      Bob    Phone  Electronics         2    500   1000
2              3  Charlie   Tablet  Electronics         1    300    300
3              4    David    Shoes      Fashion         3     50    150
4              5     Emma  T-Shirt      Fashion         2     20     40

## 15. Create a Price Level Column

**Request:**  
Create a new column named `PriceLevel`.

Rules:

- `High` if `Price >= 500`
- `Low` otherwise

**Explanation:**  
This is a simple example of creating categories from numeric data.

In [18]:
df["PriceLevel"] = df["Price"].apply(lambda price: "High" if price >= 500 else "Low")

df[["Product", "Price", "PriceLevel"]].head(10)

   Product  Price PriceLevel
0   Laptop   1000       High
1    Phone    500       High
2   Tablet    300        Low
3    Shoes     50        Low
4  T-Shirt     20        Low
5    Phone    500       High
6   Tablet    300        Low
7   Laptop   1000       High
8    Shoes     50        Low
9  T-Shirt     20        Low

## 16. Total Revenue

**Request:**  
Calculate the total revenue from all transactions.

**Explanation:**  
After creating the `Total` column, the total revenue is the sum of that column.

In [19]:
total_revenue = df["Total"].sum()

total_revenue

np.int64(12230)

## 17. Average, Minimum, and Maximum Price

**Request:**  
Find:

- Average product price
- Minimum product price
- Maximum product price

In [20]:
price_summary = {
    "Average Price": df["Price"].mean(),
    "Minimum Price": df["Price"].min(),
    "Maximum Price": df["Price"].max()
}

price_summary

{'Average Price': np.float64(374.0),
 'Minimum Price': np.int64(20),
 'Maximum Price': np.int64(1000)}

## 18. Count Transactions by Category

**Request:**  
Find how many transactions belong to each category.

**Explanation:**  
`value_counts()` counts how many times each unique value appears.

In [21]:
df["Category"].value_counts()

Category
Electronics    12
Fashion         8
Name: count, dtype: int64

## 19. Count Unique Customers and Products

**Request:**  
Find the number of unique customers and unique products.

**Explanation:**  
`nunique()` counts distinct values.

In [22]:
unique_summary = {
    "Unique Customers": df["Customer"].nunique(),
    "Unique Products": df["Product"].nunique()
}

unique_summary

{'Unique Customers': 5, 'Unique Products': 5}

## 20. Total Revenue by Customer

**Request:**  
Calculate total revenue for each customer.

**Explanation:**  
`groupby()` groups rows by customer, then `sum()` calculates the total per customer.

In [23]:
revenue_by_customer = df.groupby("Customer")["Total"].sum()

revenue_by_customer

Customer
Alice      2650
Bob        1740
Charlie    4360
David      2200
Emma       1280
Name: Total, dtype: int64

## 21. Total Quantity Sold by Product

**Request:**  
Calculate the total quantity sold for each product.

In [24]:
quantity_by_product = df.groupby("Product")["Quantity"].sum()

quantity_by_product

Product
Laptop     6
Phone      7
Shoes      9
T-Shirt    9
Tablet     7
Name: Quantity, dtype: int64

## 22. Average Price by Category

**Request:**  
Find the average price for each category.

In [25]:
avg_price_by_category = df.groupby("Category")["Price"].mean()

avg_price_by_category

Category
Electronics    600.0
Fashion         35.0
Name: Price, dtype: float64

## 23. Multiple Aggregations by Category

**Request:**  
For each category, calculate:

- Total quantity sold
- Total revenue
- Average price

**Explanation:**  
`agg()` allows us to calculate multiple summary statistics at once.

In [26]:
category_summary = df.groupby("Category").agg(
    TotalQuantity=("Quantity", "sum"),
    TotalRevenue=("Total", "sum"),
    AveragePrice=("Price", "mean")
)

category_summary

             TotalQuantity  TotalRevenue  AveragePrice
Category
Electronics             20         11600         600.0
Fashion                 18           630          35.0

## 24. Customer with the Highest Total Spending

**Request:**  
Find which customer spent the most money in total.

**Explanation:**  
First group by customer, then use `idxmax()` to find the customer with the highest value.

In [27]:
customer_revenue = df.groupby("Customer")["Total"].sum()

top_customer = customer_revenue.idxmax()
top_customer_amount = customer_revenue.max()

top_customer, top_customer_amount

('Charlie', np.int64(4360))

## 25. Product with the Highest Revenue

**Request:**  
Find which product generated the highest revenue.

In [28]:
product_revenue = df.groupby("Product")["Total"].sum()

top_product = product_revenue.idxmax()
top_product_revenue = product_revenue.max()

top_product, top_product_revenue

('Laptop', np.int64(6000))

## 26. Product Sold the Most by Quantity

**Request:**  
Find which product was sold the most based on total quantity.

In [29]:
product_quantity = df.groupby("Product")["Quantity"].sum()

most_sold_product = product_quantity.idxmax()
most_sold_quantity = product_quantity.max()

most_sold_product, most_sold_quantity

('Shoes', np.int64(9))

## 27. Sort Transactions by Total Value

**Request:**  
Sort the DataFrame by `Total` from highest to lowest.

In [30]:
df.sort_values(by="Total", ascending=False)

    TransactionID Customer  Product  ... Price  Total  PriceLevel
7               8  Charlie   Laptop  ...  1000   3000        High
0               1    Alice   Laptop  ...  1000   1000        High
10             11    Alice   Laptop  ...  1000   1000        High
1               2      Bob    Phone  ...   500   1000        High
18             19    David    Phone  ...   500   1000        High
13             14    David    Phone  ...   500   1000        High
17             18  Charlie   Laptop  ...  1000   1000        High
19             20     Emma   Tablet  ...   300    900         Low
6               7      Bob   Tablet  ...   300    600         Low
5               6    Alice    Phone  ...   500    500        High
14             15     Emma   Tablet  ...   300    300         Low
2               3  Charlie   Tablet  ...   300    300         Low
3               4    David    Shoes  ...    50    150         Low
15             16    Alice    Shoes  ...    50    150         Low
11             12      Bob    Shoes  ...    50    100         Low
12             13  Charlie  T-Shirt  ...    20     60         Low
8               9    David    Shoes  ...    50     50         Low
4               5     Emma  T-Shirt  ...    20     40         Low
9              10     Emma  T-Shirt  ...    20     40         Low
16             17      Bob  T-Shirt  ...    20     40         Low

[20 rows x 8 columns]

## 28. Top 5 Transactions by Total Value

**Request:**  
Display the 5 transactions with the highest `Total`.

**Explanation:**  
`nlargest()` is a clean way to get top N rows based on a numeric column.

In [31]:
df.nlargest(5, "Total")

    TransactionID Customer Product  ... Price  Total  PriceLevel
7               8  Charlie  Laptop  ...  1000   3000        High
0               1    Alice  Laptop  ...  1000   1000        High
1               2      Bob   Phone  ...   500   1000        High
10             11    Alice  Laptop  ...  1000   1000        High
13             14    David   Phone  ...   500   1000        High

[5 rows x 8 columns]

## 29. Transactions Above Average Total

**Request:**  
Find all transactions where `Total` is greater than the average transaction total.

In [32]:
average_total = df["Total"].mean()

df[df["Total"] > average_total]

    TransactionID Customer Product  ... Price  Total  PriceLevel
0               1    Alice  Laptop  ...  1000   1000        High
1               2      Bob   Phone  ...   500   1000        High
7               8  Charlie  Laptop  ...  1000   3000        High
10             11    Alice  Laptop  ...  1000   1000        High
13             14    David   Phone  ...   500   1000        High
17             18  Charlie  Laptop  ...  1000   1000        High
18             19    David   Phone  ...   500   1000        High
19             20     Emma  Tablet  ...   300    900         Low

[8 rows x 8 columns]

## 30. Add Customer Total Spending Using `transform`

**Request:**  
Create a new column named `CustomerTotalSpending` that shows each customer's total spending on every row.

**Explanation:**  
`transform()` returns values with the same length as the original DataFrame, so it is useful when we want group results added back to each row.

In [33]:
df["CustomerTotalSpending"] = df.groupby("Customer")["Total"].transform("sum")

df[["Customer", "Product", "Total", "CustomerTotalSpending"]].head(10)

  Customer  Product  Total  CustomerTotalSpending
0    Alice   Laptop   1000                   2650
1      Bob    Phone   1000                   1740
2  Charlie   Tablet    300                   4360
3    David    Shoes    150                   2200
4     Emma  T-Shirt     40                   1280
5    Alice    Phone    500                   2650
6      Bob   Tablet    600                   1740
7  Charlie   Laptop   3000                   4360
8    David    Shoes     50                   2200
9     Emma  T-Shirt     40                   1280

## 31. Calculate Each Transaction's Share of Customer Spending

**Request:**  
Create a new column named `ShareOfCustomerSpending`.

Formula:

`Total / CustomerTotalSpending`

**Explanation:**  
This shows how much each transaction contributed to the customer's total spending.

In [34]:
df["ShareOfCustomerSpending"] = df["Total"] / df["CustomerTotalSpending"]

df[["Customer", "Product", "Total", "CustomerTotalSpending", "ShareOfCustomerSpending"]].head(10)

  Customer  Product  Total  CustomerTotalSpending  ShareOfCustomerSpending
0    Alice   Laptop   1000                   2650                 0.377358
1      Bob    Phone   1000                   1740                 0.574713
2  Charlie   Tablet    300                   4360                 0.068807
3    David    Shoes    150                   2200                 0.068182
4     Emma  T-Shirt     40                   1280                 0.031250
5    Alice    Phone    500                   2650                 0.188679
6      Bob   Tablet    600                   1740                 0.344828
7  Charlie   Laptop   3000                   4360                 0.688073
8    David    Shoes     50                   2200                 0.022727
9     Emma  T-Shirt     40                   1280                 0.031250

## 32. Pivot Table: Revenue by Customer and Category

**Request:**  
Create a pivot table showing total revenue by `Customer` and `Category`.

**Explanation:**  
A pivot table summarizes data in a matrix format.

In [35]:
revenue_pivot = pd.pivot_table(
    df,
    values="Total",
    index="Customer",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)

revenue_pivot

Category  Electronics  Fashion
Customer
Alice            2500      150
Bob              1600      140
Charlie          4300       60
David            2000      200
Emma             1200       80

## 33. Customers Who Bought from Both Categories

**Request:**  
Find customers who bought products from both `Electronics` and `Fashion`.

**Explanation:**  
Group by customer, collect unique categories, then check which customers have both categories.

In [36]:
customer_categories = df.groupby("Customer")["Category"].unique()

customers_both_categories = customer_categories[
    customer_categories.apply(lambda categories: {"Electronics", "Fashion"}.issubset(set(categories)))
]

customers_both_categories

Customer
Alice      [Electronics, Fashion]
Bob        [Electronics, Fashion]
Charlie    [Electronics, Fashion]
David      [Fashion, Electronics]
Emma       [Fashion, Electronics]
Name: Category, dtype: object

## 34. Use `query()` for Cleaner Filtering

**Request:**  
Find all transactions where:

- `Category` is `Electronics`
- `Price` is at least 500
- `Quantity` is at least 2

**Explanation:**  
`query()` can make filtering more readable, especially when conditions are simple.

In [37]:
df.query("Category == 'Electronics' and Price >= 500 and Quantity >= 2")

    TransactionID Customer  ... CustomerTotalSpending ShareOfCustomerSpending
1               2      Bob  ...                  1740                0.574713
7               8  Charlie  ...                  4360                0.688073
13             14    David  ...                  2200                0.454545
18             19    David  ...                  2200                0.454545

[4 rows x 10 columns]

## 35. Final Business Summary Table

**Request:**  
Create a summary table by customer with:

- Number of transactions
- Total quantity
- Total spending
- Average transaction value

Sort the result by total spending descending.

**Explanation:**  
This combines grouping, aggregation, and sorting.

In [38]:
customer_summary = df.groupby("Customer").agg(
    NumberOfTransactions=("TransactionID", "count"),
    TotalQuantity=("Quantity", "sum"),
    TotalSpending=("Total", "sum"),
    AverageTransactionValue=("Total", "mean")
).sort_values(by="TotalSpending", ascending=False)

customer_summary

          NumberOfTransactions  ...  AverageTransactionValue
Customer                        ...
Charlie                      4  ...                   1090.0
Alice                        4  ...                    662.5
David                        4  ...                    550.0
Bob                          4  ...                    435.0
Emma                         4  ...                    320.0

[5 rows x 4 columns]

## 36. Export Results to Excel

**Request:**  
Export the cleaned dataset and summary tables to a new Excel file named `transactions_analysis_solution.xlsx`.

**Explanation:**  
`ExcelWriter` allows us to save multiple DataFrames into different sheets of the same Excel file.

In [39]:
with pd.ExcelWriter("transactions_analysis_solution.xlsx") as writer:
    df.to_excel(writer, sheet_name="Cleaned_Data", index=False)
    category_summary.to_excel(writer, sheet_name="Category_Summary")
    customer_summary.to_excel(writer, sheet_name="Customer_Summary")
    revenue_pivot.to_excel(writer, sheet_name="Revenue_Pivot")

print("Excel file exported successfully.")

Excel file exported successfully.

# Final Notes

This notebook covered the most important Pandas recap skills.

Students practiced:

- Data inspection
- Column and row selection
- Filtering
- New columns
- Aggregations
- Grouped analysis
- Sorting and top records
- Transform
- Pivot tables
- Exporting results